//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: battle.proto
namespace netproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BCS_Tick")]
  public partial class BCS_Tick : global::ProtoBuf.IExtensible
  {
    public BCS_Tick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BSC_Tick")]
  public partial class BSC_Tick : global::ProtoBuf.IExtensible
  {
    public BSC_Tick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BCS_None")]
  public partial class BCS_None : global::ProtoBuf.IExtensible
  {
    public BCS_None() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EBMsgIds")]
    public enum EBMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBCS_None", Value=0)]
      EBCS_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBCS_Tick", Value=1)]
      EBCS_Tick = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EBSC_Tick", Value=2)]
      EBSC_Tick = 2
    }
  
}