//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: cluster.proto
namespace netproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_Tick")]
  public partial class SS_Tick : global::ProtoBuf.IExtensible
  {
    public SS_Tick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_KickPlayer")]
  public partial class SS_KickPlayer : global::ProtoBuf.IExtensible
  {
    public SS_KickPlayer() {}
    
    private long? _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool playerIdSpecified
    {
      get { return this._playerId != null; }
      set { if (value == (this._playerId== null)) this._playerId = value ? this.playerId : (long?)null; }
    }
    private bool ShouldSerializeplayerId() { return playerIdSpecified; }
    private void ResetplayerId() { playerIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_Player2Player")]
  public partial class SS_Player2Player : global::ProtoBuf.IExtensible
  {
    public SS_Player2Player() {}
    
    private long? _fromPlayerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fromPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? fromPlayerId
    {
      get { return _fromPlayerId; }
      set { _fromPlayerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromPlayerIdSpecified
    {
      get { return this._fromPlayerId != null; }
      set { if (value == (this._fromPlayerId== null)) this._fromPlayerId = value ? this.fromPlayerId : (long?)null; }
    }
    private bool ShouldSerializefromPlayerId() { return fromPlayerIdSpecified; }
    private void ResetfromPlayerId() { fromPlayerIdSpecified = false; }
    
    private long? _toPlayerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"toPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? toPlayerId
    {
      get { return _toPlayerId; }
      set { _toPlayerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toPlayerIdSpecified
    {
      get { return this._toPlayerId != null; }
      set { if (value == (this._toPlayerId== null)) this._toPlayerId = value ? this.toPlayerId : (long?)null; }
    }
    private bool ShouldSerializetoPlayerId() { return toPlayerIdSpecified; }
    private void ResettoPlayerId() { toPlayerIdSpecified = false; }
    
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return this._data != null; }
      set { if (value == (this._data== null)) this._data = value ? this.data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_PlayerBaseappRedirect")]
  public partial class SS_PlayerBaseappRedirect : global::ProtoBuf.IExtensible
  {
    public SS_PlayerBaseappRedirect() {}
    
    private long? _playerId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool playerIdSpecified
    {
      get { return this._playerId != null; }
      set { if (value == (this._playerId== null)) this._playerId = value ? this.playerId : (long?)null; }
    }
    private bool ShouldSerializeplayerId() { return playerIdSpecified; }
    private void ResetplayerId() { playerIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_ForwardPlayerMsg")]
  public partial class SS_ForwardPlayerMsg : global::ProtoBuf.IExtensible
  {
    public SS_ForwardPlayerMsg() {}
    
    private long? _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool playerIdSpecified
    {
      get { return this._playerId != null; }
      set { if (value == (this._playerId== null)) this._playerId = value ? this.playerId : (long?)null; }
    }
    private bool ShouldSerializeplayerId() { return playerIdSpecified; }
    private void ResetplayerId() { playerIdSpecified = false; }
    
    private int? _msgId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgIdSpecified
    {
      get { return this._msgId != null; }
      set { if (value == (this._msgId== null)) this._msgId = value ? this.msgId : (int?)null; }
    }
    private bool ShouldSerializemsgId() { return msgIdSpecified; }
    private void ResetmsgId() { msgIdSpecified = false; }
    
    private byte[] _msgs;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msgs
    {
      get { return _msgs; }
      set { _msgs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgsSpecified
    {
      get { return this._msgs != null; }
      set { if (value == (this._msgs== null)) this._msgs = value ? this.msgs : (byte[])null; }
    }
    private bool ShouldSerializemsgs() { return msgsSpecified; }
    private void Resetmsgs() { msgsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_ForwardPlayerGuideMsg")]
  public partial class SS_ForwardPlayerGuideMsg : global::ProtoBuf.IExtensible
  {
    public SS_ForwardPlayerGuideMsg() {}
    
    private long? _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool playerIdSpecified
    {
      get { return this._playerId != null; }
      set { if (value == (this._playerId== null)) this._playerId = value ? this.playerId : (long?)null; }
    }
    private bool ShouldSerializeplayerId() { return playerIdSpecified; }
    private void ResetplayerId() { playerIdSpecified = false; }
    
    private long? _guideId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guideId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? guideId
    {
      get { return _guideId; }
      set { _guideId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool guideIdSpecified
    {
      get { return this._guideId != null; }
      set { if (value == (this._guideId== null)) this._guideId = value ? this.guideId : (long?)null; }
    }
    private bool ShouldSerializeguideId() { return guideIdSpecified; }
    private void ResetguideId() { guideIdSpecified = false; }
    
    private int? _msgId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgIdSpecified
    {
      get { return this._msgId != null; }
      set { if (value == (this._msgId== null)) this._msgId = value ? this.msgId : (int?)null; }
    }
    private bool ShouldSerializemsgId() { return msgIdSpecified; }
    private void ResetmsgId() { msgIdSpecified = false; }
    
    private byte[] _msgs;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"msgs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msgs
    {
      get { return _msgs; }
      set { _msgs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgsSpecified
    {
      get { return this._msgs != null; }
      set { if (value == (this._msgs== null)) this._msgs = value ? this.msgs : (byte[])null; }
    }
    private bool ShouldSerializemsgs() { return msgsSpecified; }
    private void Resetmsgs() { msgsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SS_None")]
  public partial class SS_None : global::ProtoBuf.IExtensible
  {
    public SS_None() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ECMsgIds")]
    public enum ECMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_None", Value=0)]
      ESS_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_Tick", Value=1)]
      ESS_Tick = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_KickPlayer", Value=11)]
      ESS_KickPlayer = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_Player2Player", Value=12)]
      ESS_Player2Player = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_PlayerBaseappRedirect", Value=13)]
      ESS_PlayerBaseappRedirect = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_ForwardPlayerMsg", Value=14)]
      ESS_ForwardPlayerMsg = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESS_ForwardPlayerGuideMsg", Value=15)]
      ESS_ForwardPlayerGuideMsg = 15
    }
  
}