//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: logic.proto
namespace netproto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_TestSyncBaseInfo")]
  public partial class CS_TestSyncBaseInfo : global::ProtoBuf.IExtensible
  {
    public CS_TestSyncBaseInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_TestSyncBaseInfo")]
  public partial class SC_TestSyncBaseInfo : global::ProtoBuf.IExtensible
  {
    public SC_TestSyncBaseInfo() {}
    
    private netproto.E_Code? _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public netproto.E_Code? code
    {
      get { return _code; }
      set { _code = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool codeSpecified
    {
      get { return this._code != null; }
      set { if (value == (this._code== null)) this._code = value ? this.code : (netproto.E_Code?)null; }
    }
    private bool ShouldSerializecode() { return codeSpecified; }
    private void Resetcode() { codeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Tick")]
  public partial class CS_Tick : global::ProtoBuf.IExtensible
  {
    public CS_Tick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Tick")]
  public partial class SC_Tick : global::ProtoBuf.IExtensible
  {
    public SC_Tick() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_Login")]
  public partial class CS_Login : global::ProtoBuf.IExtensible
  {
    public CS_Login() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool tokenSpecified
    {
      get { return this._token != null; }
      set { if (value == (this._token== null)) this._token = value ? this.token : (string)null; }
    }
    private bool ShouldSerializetoken() { return tokenSpecified; }
    private void Resettoken() { tokenSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_Login")]
  public partial class SC_Login : global::ProtoBuf.IExtensible
  {
    public SC_Login() {}
    
    private long? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? id
    {
      get { return _id; }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (long?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private netproto.E_Code? _code;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public netproto.E_Code? code
    {
      get { return _code; }
      set { _code = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool codeSpecified
    {
      get { return this._code != null; }
      set { if (value == (this._code== null)) this._code = value ? this.code : (netproto.E_Code?)null; }
    }
    private bool ShouldSerializecode() { return codeSpecified; }
    private void Resetcode() { codeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_P2P")]
  public partial class CS_P2P : global::ProtoBuf.IExtensible
  {
    public CS_P2P() {}
    
    private long? _from;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? from
    {
      get { return _from; }
      set { _from = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromSpecified
    {
      get { return this._from != null; }
      set { if (value == (this._from== null)) this._from = value ? this.from : (long?)null; }
    }
    private bool ShouldSerializefrom() { return fromSpecified; }
    private void Resetfrom() { fromSpecified = false; }
    
    private long? _to;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? to
    {
      get { return _to; }
      set { _to = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toSpecified
    {
      get { return this._to != null; }
      set { if (value == (this._to== null)) this._to = value ? this.to : (long?)null; }
    }
    private bool ShouldSerializeto() { return toSpecified; }
    private void Resetto() { toSpecified = false; }
    
    private byte[] _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (byte[])null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_P2P")]
  public partial class SC_P2P : global::ProtoBuf.IExtensible
  {
    public SC_P2P() {}
    
    private long? _from;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? from
    {
      get { return _from; }
      set { _from = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fromSpecified
    {
      get { return this._from != null; }
      set { if (value == (this._from== null)) this._from = value ? this.from : (long?)null; }
    }
    private bool ShouldSerializefrom() { return fromSpecified; }
    private void Resetfrom() { fromSpecified = false; }
    
    private long? _to;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? to
    {
      get { return _to; }
      set { _to = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool toSpecified
    {
      get { return this._to != null; }
      set { if (value == (this._to== null)) this._to = value ? this.to : (long?)null; }
    }
    private bool ShouldSerializeto() { return toSpecified; }
    private void Resetto() { toSpecified = false; }
    
    private byte[] _msg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool msgSpecified
    {
      get { return this._msg != null; }
      set { if (value == (this._msg== null)) this._msg = value ? this.msg : (byte[])null; }
    }
    private bool ShouldSerializemsg() { return msgSpecified; }
    private void Resetmsg() { msgSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_GuideDonate")]
  public partial class CS_GuideDonate : global::ProtoBuf.IExtensible
  {
    public CS_GuideDonate() {}
    
    private long? _guideId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guideId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long? guideId
    {
      get { return _guideId; }
      set { _guideId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool guideIdSpecified
    {
      get { return this._guideId != null; }
      set { if (value == (this._guideId== null)) this._guideId = value ? this.guideId : (long?)null; }
    }
    private bool ShouldSerializeguideId() { return guideIdSpecified; }
    private void ResetguideId() { guideIdSpecified = false; }
    
    private int? _gold;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int? gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool goldSpecified
    {
      get { return this._gold != null; }
      set { if (value == (this._gold== null)) this._gold = value ? this.gold : (int?)null; }
    }
    private bool ShouldSerializegold() { return goldSpecified; }
    private void Resetgold() { goldSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_None")]
  public partial class CS_None : global::ProtoBuf.IExtensible
  {
    public CS_None() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"E_Code")]
    public enum E_Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_ERROR", Value=0)]
      E_ERROR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_OK", Value=1)]
      E_OK = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_RELOGIN", Value=2)]
      E_RELOGIN = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_NONE_EXIST", Value=3)]
      E_NONE_EXIST = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_UNKNOWN", Value=4)]
      E_UNKNOWN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_SERVER_INTERNAL_ERROR", Value=5)]
      E_SERVER_INTERNAL_ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_INVALID_PARAM", Value=6)]
      E_INVALID_PARAM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"E_INVALID_OPT", Value=7)]
      E_INVALID_OPT = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EMsgIds")]
    public enum EMsgIds
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECS_None", Value=0)]
      ECS_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECS_TestSyncBaseInfo", Value=90)]
      ECS_TestSyncBaseInfo = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESC_TestSyncBaseInfo", Value=91)]
      ESC_TestSyncBaseInfo = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECS_Login", Value=101)]
      ECS_Login = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESC_Login", Value=103)]
      ESC_Login = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECS_Tick", Value=104)]
      ECS_Tick = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESC_Tick", Value=105)]
      ESC_Tick = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECS_P2P", Value=106)]
      ECS_P2P = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ESC_P2P", Value=107)]
      ESC_P2P = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECS_GuideDonate", Value=108)]
      ECS_GuideDonate = 108
    }
  
}