// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playerdata.proto

package netproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerDatabaseInfo struct {
	Key                  *int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *BaseInfo `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerDatabaseInfo) Reset()         { *m = PlayerDatabaseInfo{} }
func (m *PlayerDatabaseInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerDatabaseInfo) ProtoMessage()    {}
func (*PlayerDatabaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{0}
}
func (m *PlayerDatabaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDatabaseInfo.Unmarshal(m, b)
}
func (m *PlayerDatabaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDatabaseInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerDatabaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDatabaseInfo.Merge(dst, src)
}
func (m *PlayerDatabaseInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerDatabaseInfo.Size(m)
}
func (m *PlayerDatabaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDatabaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDatabaseInfo proto.InternalMessageInfo

func (m *PlayerDatabaseInfo) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerDatabaseInfo) GetVal() *BaseInfo {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerDatapets struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *Pet     `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDatapets) Reset()         { *m = PlayerDatapets{} }
func (m *PlayerDatapets) String() string { return proto.CompactTextString(m) }
func (*PlayerDatapets) ProtoMessage()    {}
func (*PlayerDatapets) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{1}
}
func (m *PlayerDatapets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDatapets.Unmarshal(m, b)
}
func (m *PlayerDatapets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDatapets.Marshal(b, m, deterministic)
}
func (dst *PlayerDatapets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDatapets.Merge(dst, src)
}
func (m *PlayerDatapets) XXX_Size() int {
	return xxx_messageInfo_PlayerDatapets.Size(m)
}
func (m *PlayerDatapets) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDatapets.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDatapets proto.InternalMessageInfo

func (m *PlayerDatapets) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerDatapets) GetVal() *Pet {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerDatadaily struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *Daily   `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDatadaily) Reset()         { *m = PlayerDatadaily{} }
func (m *PlayerDatadaily) String() string { return proto.CompactTextString(m) }
func (*PlayerDatadaily) ProtoMessage()    {}
func (*PlayerDatadaily) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{2}
}
func (m *PlayerDatadaily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDatadaily.Unmarshal(m, b)
}
func (m *PlayerDatadaily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDatadaily.Marshal(b, m, deterministic)
}
func (dst *PlayerDatadaily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDatadaily.Merge(dst, src)
}
func (m *PlayerDatadaily) XXX_Size() int {
	return xxx_messageInfo_PlayerDatadaily.Size(m)
}
func (m *PlayerDatadaily) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDatadaily.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDatadaily proto.InternalMessageInfo

func (m *PlayerDatadaily) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerDatadaily) GetVal() *Daily {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerDatapacks struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *Pack    `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerDatapacks) Reset()         { *m = PlayerDatapacks{} }
func (m *PlayerDatapacks) String() string { return proto.CompactTextString(m) }
func (*PlayerDatapacks) ProtoMessage()    {}
func (*PlayerDatapacks) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{3}
}
func (m *PlayerDatapacks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDatapacks.Unmarshal(m, b)
}
func (m *PlayerDatapacks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDatapacks.Marshal(b, m, deterministic)
}
func (dst *PlayerDatapacks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDatapacks.Merge(dst, src)
}
func (m *PlayerDatapacks) XXX_Size() int {
	return xxx_messageInfo_PlayerDatapacks.Size(m)
}
func (m *PlayerDatapacks) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDatapacks.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDatapacks proto.InternalMessageInfo

func (m *PlayerDatapacks) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerDatapacks) GetVal() *Pack {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerInfoserverTime struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfoserverTime) Reset()         { *m = PlayerInfoserverTime{} }
func (m *PlayerInfoserverTime) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoserverTime) ProtoMessage()    {}
func (*PlayerInfoserverTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{4}
}
func (m *PlayerInfoserverTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfoserverTime.Unmarshal(m, b)
}
func (m *PlayerInfoserverTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfoserverTime.Marshal(b, m, deterministic)
}
func (dst *PlayerInfoserverTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfoserverTime.Merge(dst, src)
}
func (m *PlayerInfoserverTime) XXX_Size() int {
	return xxx_messageInfo_PlayerInfoserverTime.Size(m)
}
func (m *PlayerInfoserverTime) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfoserverTime.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfoserverTime proto.InternalMessageInfo

func (m *PlayerInfoserverTime) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerInfoserverTime) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type PlayerInfoserverName struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfoserverName) Reset()         { *m = PlayerInfoserverName{} }
func (m *PlayerInfoserverName) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoserverName) ProtoMessage()    {}
func (*PlayerInfoserverName) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{5}
}
func (m *PlayerInfoserverName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfoserverName.Unmarshal(m, b)
}
func (m *PlayerInfoserverName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfoserverName.Marshal(b, m, deterministic)
}
func (dst *PlayerInfoserverName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfoserverName.Merge(dst, src)
}
func (m *PlayerInfoserverName) XXX_Size() int {
	return xxx_messageInfo_PlayerInfoserverName.Size(m)
}
func (m *PlayerInfoserverName) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfoserverName.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfoserverName proto.InternalMessageInfo

func (m *PlayerInfoserverName) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerInfoserverName) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type BaseInfoid struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoid) Reset()         { *m = BaseInfoid{} }
func (m *BaseInfoid) String() string { return proto.CompactTextString(m) }
func (*BaseInfoid) ProtoMessage()    {}
func (*BaseInfoid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{6}
}
func (m *BaseInfoid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoid.Unmarshal(m, b)
}
func (m *BaseInfoid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoid.Marshal(b, m, deterministic)
}
func (dst *BaseInfoid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoid.Merge(dst, src)
}
func (m *BaseInfoid) XXX_Size() int {
	return xxx_messageInfo_BaseInfoid.Size(m)
}
func (m *BaseInfoid) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoid.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoid proto.InternalMessageInfo

func (m *BaseInfoid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfoid) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfoname struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoname) Reset()         { *m = BaseInfoname{} }
func (m *BaseInfoname) String() string { return proto.CompactTextString(m) }
func (*BaseInfoname) ProtoMessage()    {}
func (*BaseInfoname) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{7}
}
func (m *BaseInfoname) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoname.Unmarshal(m, b)
}
func (m *BaseInfoname) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoname.Marshal(b, m, deterministic)
}
func (dst *BaseInfoname) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoname.Merge(dst, src)
}
func (m *BaseInfoname) XXX_Size() int {
	return xxx_messageInfo_BaseInfoname.Size(m)
}
func (m *BaseInfoname) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoname.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoname proto.InternalMessageInfo

func (m *BaseInfoname) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfoname) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type BaseInfolevel struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfolevel) Reset()         { *m = BaseInfolevel{} }
func (m *BaseInfolevel) String() string { return proto.CompactTextString(m) }
func (*BaseInfolevel) ProtoMessage()    {}
func (*BaseInfolevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{8}
}
func (m *BaseInfolevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfolevel.Unmarshal(m, b)
}
func (m *BaseInfolevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfolevel.Marshal(b, m, deterministic)
}
func (dst *BaseInfolevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfolevel.Merge(dst, src)
}
func (m *BaseInfolevel) XXX_Size() int {
	return xxx_messageInfo_BaseInfolevel.Size(m)
}
func (m *BaseInfolevel) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfolevel.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfolevel proto.InternalMessageInfo

func (m *BaseInfolevel) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfolevel) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfogold struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfogold) Reset()         { *m = BaseInfogold{} }
func (m *BaseInfogold) String() string { return proto.CompactTextString(m) }
func (*BaseInfogold) ProtoMessage()    {}
func (*BaseInfogold) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{9}
}
func (m *BaseInfogold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfogold.Unmarshal(m, b)
}
func (m *BaseInfogold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfogold.Marshal(b, m, deterministic)
}
func (dst *BaseInfogold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfogold.Merge(dst, src)
}
func (m *BaseInfogold) XXX_Size() int {
	return xxx_messageInfo_BaseInfogold.Size(m)
}
func (m *BaseInfogold) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfogold.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfogold proto.InternalMessageInfo

func (m *BaseInfogold) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfogold) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfoexp struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoexp) Reset()         { *m = BaseInfoexp{} }
func (m *BaseInfoexp) String() string { return proto.CompactTextString(m) }
func (*BaseInfoexp) ProtoMessage()    {}
func (*BaseInfoexp) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{10}
}
func (m *BaseInfoexp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoexp.Unmarshal(m, b)
}
func (m *BaseInfoexp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoexp.Marshal(b, m, deterministic)
}
func (dst *BaseInfoexp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoexp.Merge(dst, src)
}
func (m *BaseInfoexp) XXX_Size() int {
	return xxx_messageInfo_BaseInfoexp.Size(m)
}
func (m *BaseInfoexp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoexp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoexp proto.InternalMessageInfo

func (m *BaseInfoexp) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfoexp) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Petid struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Petid) Reset()         { *m = Petid{} }
func (m *Petid) String() string { return proto.CompactTextString(m) }
func (*Petid) ProtoMessage()    {}
func (*Petid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{11}
}
func (m *Petid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Petid.Unmarshal(m, b)
}
func (m *Petid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Petid.Marshal(b, m, deterministic)
}
func (dst *Petid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Petid.Merge(dst, src)
}
func (m *Petid) XXX_Size() int {
	return xxx_messageInfo_Petid.Size(m)
}
func (m *Petid) XXX_DiscardUnknown() {
	xxx_messageInfo_Petid.DiscardUnknown(m)
}

var xxx_messageInfo_Petid proto.InternalMessageInfo

func (m *Petid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Petid) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Petlevel struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Petlevel) Reset()         { *m = Petlevel{} }
func (m *Petlevel) String() string { return proto.CompactTextString(m) }
func (*Petlevel) ProtoMessage()    {}
func (*Petlevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{12}
}
func (m *Petlevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Petlevel.Unmarshal(m, b)
}
func (m *Petlevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Petlevel.Marshal(b, m, deterministic)
}
func (dst *Petlevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Petlevel.Merge(dst, src)
}
func (m *Petlevel) XXX_Size() int {
	return xxx_messageInfo_Petlevel.Size(m)
}
func (m *Petlevel) XXX_DiscardUnknown() {
	xxx_messageInfo_Petlevel.DiscardUnknown(m)
}

var xxx_messageInfo_Petlevel proto.InternalMessageInfo

func (m *Petlevel) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Petlevel) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Petpack struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Petpack) Reset()         { *m = Petpack{} }
func (m *Petpack) String() string { return proto.CompactTextString(m) }
func (*Petpack) ProtoMessage()    {}
func (*Petpack) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{13}
}
func (m *Petpack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Petpack.Unmarshal(m, b)
}
func (m *Petpack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Petpack.Marshal(b, m, deterministic)
}
func (dst *Petpack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Petpack.Merge(dst, src)
}
func (m *Petpack) XXX_Size() int {
	return xxx_messageInfo_Petpack.Size(m)
}
func (m *Petpack) XXX_DiscardUnknown() {
	xxx_messageInfo_Petpack.DiscardUnknown(m)
}

var xxx_messageInfo_Petpack proto.InternalMessageInfo

func (m *Petpack) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Petpack) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Packid struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packid) Reset()         { *m = Packid{} }
func (m *Packid) String() string { return proto.CompactTextString(m) }
func (*Packid) ProtoMessage()    {}
func (*Packid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{14}
}
func (m *Packid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packid.Unmarshal(m, b)
}
func (m *Packid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packid.Marshal(b, m, deterministic)
}
func (dst *Packid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packid.Merge(dst, src)
}
func (m *Packid) XXX_Size() int {
	return xxx_messageInfo_Packid.Size(m)
}
func (m *Packid) XXX_DiscardUnknown() {
	xxx_messageInfo_Packid.DiscardUnknown(m)
}

var xxx_messageInfo_Packid proto.InternalMessageInfo

func (m *Packid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Packid) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Packnum struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packnum) Reset()         { *m = Packnum{} }
func (m *Packnum) String() string { return proto.CompactTextString(m) }
func (*Packnum) ProtoMessage()    {}
func (*Packnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{15}
}
func (m *Packnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packnum.Unmarshal(m, b)
}
func (m *Packnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packnum.Marshal(b, m, deterministic)
}
func (dst *Packnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packnum.Merge(dst, src)
}
func (m *Packnum) XXX_Size() int {
	return xxx_messageInfo_Packnum.Size(m)
}
func (m *Packnum) XXX_DiscardUnknown() {
	xxx_messageInfo_Packnum.DiscardUnknown(m)
}

var xxx_messageInfo_Packnum proto.InternalMessageInfo

func (m *Packnum) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Packnum) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type DailylastUpdateTime struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DailylastUpdateTime) Reset()         { *m = DailylastUpdateTime{} }
func (m *DailylastUpdateTime) String() string { return proto.CompactTextString(m) }
func (*DailylastUpdateTime) ProtoMessage()    {}
func (*DailylastUpdateTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{16}
}
func (m *DailylastUpdateTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DailylastUpdateTime.Unmarshal(m, b)
}
func (m *DailylastUpdateTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DailylastUpdateTime.Marshal(b, m, deterministic)
}
func (dst *DailylastUpdateTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DailylastUpdateTime.Merge(dst, src)
}
func (m *DailylastUpdateTime) XXX_Size() int {
	return xxx_messageInfo_DailylastUpdateTime.Size(m)
}
func (m *DailylastUpdateTime) XXX_DiscardUnknown() {
	xxx_messageInfo_DailylastUpdateTime.DiscardUnknown(m)
}

var xxx_messageInfo_DailylastUpdateTime proto.InternalMessageInfo

func (m *DailylastUpdateTime) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *DailylastUpdateTime) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type Dailysign struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *bool    `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dailysign) Reset()         { *m = Dailysign{} }
func (m *Dailysign) String() string { return proto.CompactTextString(m) }
func (*Dailysign) ProtoMessage()    {}
func (*Dailysign) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{17}
}
func (m *Dailysign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dailysign.Unmarshal(m, b)
}
func (m *Dailysign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dailysign.Marshal(b, m, deterministic)
}
func (dst *Dailysign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dailysign.Merge(dst, src)
}
func (m *Dailysign) XXX_Size() int {
	return xxx_messageInfo_Dailysign.Size(m)
}
func (m *Dailysign) XXX_DiscardUnknown() {
	xxx_messageInfo_Dailysign.DiscardUnknown(m)
}

var xxx_messageInfo_Dailysign proto.InternalMessageInfo

func (m *Dailysign) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *Dailysign) GetVal() bool {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return false
}

type TestListid struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestListid) Reset()         { *m = TestListid{} }
func (m *TestListid) String() string { return proto.CompactTextString(m) }
func (*TestListid) ProtoMessage()    {}
func (*TestListid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{18}
}
func (m *TestListid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListid.Unmarshal(m, b)
}
func (m *TestListid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListid.Marshal(b, m, deterministic)
}
func (dst *TestListid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListid.Merge(dst, src)
}
func (m *TestListid) XXX_Size() int {
	return xxx_messageInfo_TestListid.Size(m)
}
func (m *TestListid) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListid.DiscardUnknown(m)
}

var xxx_messageInfo_TestListid proto.InternalMessageInfo

func (m *TestListid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListid) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestListListPrimitiveInt struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestListListPrimitiveInt) Reset()         { *m = TestListListPrimitiveInt{} }
func (m *TestListListPrimitiveInt) String() string { return proto.CompactTextString(m) }
func (*TestListListPrimitiveInt) ProtoMessage()    {}
func (*TestListListPrimitiveInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{19}
}
func (m *TestListListPrimitiveInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListListPrimitiveInt.Unmarshal(m, b)
}
func (m *TestListListPrimitiveInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListListPrimitiveInt.Marshal(b, m, deterministic)
}
func (dst *TestListListPrimitiveInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListListPrimitiveInt.Merge(dst, src)
}
func (m *TestListListPrimitiveInt) XXX_Size() int {
	return xxx_messageInfo_TestListListPrimitiveInt.Size(m)
}
func (m *TestListListPrimitiveInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListListPrimitiveInt.DiscardUnknown(m)
}

var xxx_messageInfo_TestListListPrimitiveInt proto.InternalMessageInfo

func (m *TestListListPrimitiveInt) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListListPrimitiveInt) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestListListPrimitiveStr struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestListListPrimitiveStr) Reset()         { *m = TestListListPrimitiveStr{} }
func (m *TestListListPrimitiveStr) String() string { return proto.CompactTextString(m) }
func (*TestListListPrimitiveStr) ProtoMessage()    {}
func (*TestListListPrimitiveStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{20}
}
func (m *TestListListPrimitiveStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListListPrimitiveStr.Unmarshal(m, b)
}
func (m *TestListListPrimitiveStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListListPrimitiveStr.Marshal(b, m, deterministic)
}
func (dst *TestListListPrimitiveStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListListPrimitiveStr.Merge(dst, src)
}
func (m *TestListListPrimitiveStr) XXX_Size() int {
	return xxx_messageInfo_TestListListPrimitiveStr.Size(m)
}
func (m *TestListListPrimitiveStr) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListListPrimitiveStr.DiscardUnknown(m)
}

var xxx_messageInfo_TestListListPrimitiveStr proto.InternalMessageInfo

func (m *TestListListPrimitiveStr) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListListPrimitiveStr) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TestListListPrimitiveCom struct {
	Key                  *int32      `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *PlayerData `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestListListPrimitiveCom) Reset()         { *m = TestListListPrimitiveCom{} }
func (m *TestListListPrimitiveCom) String() string { return proto.CompactTextString(m) }
func (*TestListListPrimitiveCom) ProtoMessage()    {}
func (*TestListListPrimitiveCom) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{21}
}
func (m *TestListListPrimitiveCom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListListPrimitiveCom.Unmarshal(m, b)
}
func (m *TestListListPrimitiveCom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListListPrimitiveCom.Marshal(b, m, deterministic)
}
func (dst *TestListListPrimitiveCom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListListPrimitiveCom.Merge(dst, src)
}
func (m *TestListListPrimitiveCom) XXX_Size() int {
	return xxx_messageInfo_TestListListPrimitiveCom.Size(m)
}
func (m *TestListListPrimitiveCom) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListListPrimitiveCom.DiscardUnknown(m)
}

var xxx_messageInfo_TestListListPrimitiveCom proto.InternalMessageInfo

func (m *TestListListPrimitiveCom) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListListPrimitiveCom) GetVal() *PlayerData {
	if m != nil {
		return m.Val
	}
	return nil
}

type TestMapid struct {
	Key                  *int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *BaseInfo `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TestMapid) Reset()         { *m = TestMapid{} }
func (m *TestMapid) String() string { return proto.CompactTextString(m) }
func (*TestMapid) ProtoMessage()    {}
func (*TestMapid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{22}
}
func (m *TestMapid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapid.Unmarshal(m, b)
}
func (m *TestMapid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapid.Marshal(b, m, deterministic)
}
func (dst *TestMapid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapid.Merge(dst, src)
}
func (m *TestMapid) XXX_Size() int {
	return xxx_messageInfo_TestMapid.Size(m)
}
func (m *TestMapid) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapid.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapid proto.InternalMessageInfo

func (m *TestMapid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapid) GetVal() *BaseInfo {
	if m != nil {
		return m.Val
	}
	return nil
}

type TestMapMapPrimitiveIntInt struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveIntInt) Reset()         { *m = TestMapMapPrimitiveIntInt{} }
func (m *TestMapMapPrimitiveIntInt) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveIntInt) ProtoMessage()    {}
func (*TestMapMapPrimitiveIntInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{23}
}
func (m *TestMapMapPrimitiveIntInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveIntInt.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveIntInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveIntInt.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveIntInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveIntInt.Merge(dst, src)
}
func (m *TestMapMapPrimitiveIntInt) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveIntInt.Size(m)
}
func (m *TestMapMapPrimitiveIntInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveIntInt.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveIntInt proto.InternalMessageInfo

func (m *TestMapMapPrimitiveIntInt) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapMapPrimitiveIntInt) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestMapMapPrimitiveIntStr struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveIntStr) Reset()         { *m = TestMapMapPrimitiveIntStr{} }
func (m *TestMapMapPrimitiveIntStr) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveIntStr) ProtoMessage()    {}
func (*TestMapMapPrimitiveIntStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{24}
}
func (m *TestMapMapPrimitiveIntStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveIntStr.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveIntStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveIntStr.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveIntStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveIntStr.Merge(dst, src)
}
func (m *TestMapMapPrimitiveIntStr) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveIntStr.Size(m)
}
func (m *TestMapMapPrimitiveIntStr) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveIntStr.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveIntStr proto.InternalMessageInfo

func (m *TestMapMapPrimitiveIntStr) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapMapPrimitiveIntStr) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TestMapMapPrimitiveStrInt struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveStrInt) Reset()         { *m = TestMapMapPrimitiveStrInt{} }
func (m *TestMapMapPrimitiveStrInt) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveStrInt) ProtoMessage()    {}
func (*TestMapMapPrimitiveStrInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{25}
}
func (m *TestMapMapPrimitiveStrInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveStrInt.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveStrInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveStrInt.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveStrInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveStrInt.Merge(dst, src)
}
func (m *TestMapMapPrimitiveStrInt) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveStrInt.Size(m)
}
func (m *TestMapMapPrimitiveStrInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveStrInt.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveStrInt proto.InternalMessageInfo

func (m *TestMapMapPrimitiveStrInt) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TestMapMapPrimitiveStrInt) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestMapMapPrimitiveStrStr struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveStrStr) Reset()         { *m = TestMapMapPrimitiveStrStr{} }
func (m *TestMapMapPrimitiveStrStr) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveStrStr) ProtoMessage()    {}
func (*TestMapMapPrimitiveStrStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{26}
}
func (m *TestMapMapPrimitiveStrStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveStrStr.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveStrStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveStrStr.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveStrStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveStrStr.Merge(dst, src)
}
func (m *TestMapMapPrimitiveStrStr) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveStrStr.Size(m)
}
func (m *TestMapMapPrimitiveStrStr) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveStrStr.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveStrStr proto.InternalMessageInfo

func (m *TestMapMapPrimitiveStrStr) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TestMapMapPrimitiveStrStr) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TestMapMapPrimitiveIntCom struct {
	Key                  *int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *BaseInfo `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TestMapMapPrimitiveIntCom) Reset()         { *m = TestMapMapPrimitiveIntCom{} }
func (m *TestMapMapPrimitiveIntCom) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveIntCom) ProtoMessage()    {}
func (*TestMapMapPrimitiveIntCom) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{27}
}
func (m *TestMapMapPrimitiveIntCom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveIntCom.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveIntCom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveIntCom.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveIntCom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveIntCom.Merge(dst, src)
}
func (m *TestMapMapPrimitiveIntCom) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveIntCom.Size(m)
}
func (m *TestMapMapPrimitiveIntCom) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveIntCom.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveIntCom proto.InternalMessageInfo

func (m *TestMapMapPrimitiveIntCom) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapMapPrimitiveIntCom) GetVal() *BaseInfo {
	if m != nil {
		return m.Val
	}
	return nil
}

type TestMapMapPrimitiveStrCom struct {
	Key                  *string     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val                  *PlayerData `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestMapMapPrimitiveStrCom) Reset()         { *m = TestMapMapPrimitiveStrCom{} }
func (m *TestMapMapPrimitiveStrCom) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveStrCom) ProtoMessage()    {}
func (*TestMapMapPrimitiveStrCom) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{28}
}
func (m *TestMapMapPrimitiveStrCom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveStrCom.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveStrCom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveStrCom.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveStrCom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveStrCom.Merge(dst, src)
}
func (m *TestMapMapPrimitiveStrCom) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveStrCom.Size(m)
}
func (m *TestMapMapPrimitiveStrCom) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveStrCom.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveStrCom proto.InternalMessageInfo

func (m *TestMapMapPrimitiveStrCom) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TestMapMapPrimitiveStrCom) GetVal() *PlayerData {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerData struct {
	BaseInfo             *BaseInfo          `protobuf:"bytes,1,opt,name=baseInfo" json:"baseInfo,omitempty"`
	Pets                 []*PlayerDatapets  `protobuf:"bytes,2,rep,name=pets" json:"pets,omitempty"`
	Daily                *Daily             `protobuf:"bytes,3,opt,name=daily" json:"daily,omitempty"`
	Packs                []*PlayerDatapacks `protobuf:"bytes,4,rep,name=packs" json:"packs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{29}
}
func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (dst *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(dst, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetBaseInfo() *BaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

func (m *PlayerData) GetPets() []*PlayerDatapets {
	if m != nil {
		return m.Pets
	}
	return nil
}

func (m *PlayerData) GetDaily() *Daily {
	if m != nil {
		return m.Daily
	}
	return nil
}

func (m *PlayerData) GetPacks() []*PlayerDatapacks {
	if m != nil {
		return m.Packs
	}
	return nil
}

type PlayerInfo struct {
	ServerTime           *int64   `protobuf:"varint,1,opt,name=serverTime" json:"serverTime,omitempty"`
	ServerName           *string  `protobuf:"bytes,2,opt,name=serverName" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{30}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *PlayerInfo) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

type BaseInfo struct {
	Id                   *int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level                *int32   `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Gold                 *int32   `protobuf:"varint,4,opt,name=gold" json:"gold,omitempty"`
	Exp                  *int32   `protobuf:"varint,5,opt,name=exp" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{31}
}
func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (dst *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(dst, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BaseInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BaseInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *BaseInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *BaseInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

type Pet struct {
	Id                   *int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Level                *int32   `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Pack                 *int32   `protobuf:"varint,3,opt,name=pack" json:"pack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pet) Reset()         { *m = Pet{} }
func (m *Pet) String() string { return proto.CompactTextString(m) }
func (*Pet) ProtoMessage()    {}
func (*Pet) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{32}
}
func (m *Pet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pet.Unmarshal(m, b)
}
func (m *Pet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pet.Marshal(b, m, deterministic)
}
func (dst *Pet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pet.Merge(dst, src)
}
func (m *Pet) XXX_Size() int {
	return xxx_messageInfo_Pet.Size(m)
}
func (m *Pet) XXX_DiscardUnknown() {
	xxx_messageInfo_Pet.DiscardUnknown(m)
}

var xxx_messageInfo_Pet proto.InternalMessageInfo

func (m *Pet) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Pet) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Pet) GetPack() int32 {
	if m != nil && m.Pack != nil {
		return *m.Pack
	}
	return 0
}

type Pack struct {
	Id                   *int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Num                  *int64   `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pack) Reset()         { *m = Pack{} }
func (m *Pack) String() string { return proto.CompactTextString(m) }
func (*Pack) ProtoMessage()    {}
func (*Pack) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{33}
}
func (m *Pack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pack.Unmarshal(m, b)
}
func (m *Pack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pack.Marshal(b, m, deterministic)
}
func (dst *Pack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pack.Merge(dst, src)
}
func (m *Pack) XXX_Size() int {
	return xxx_messageInfo_Pack.Size(m)
}
func (m *Pack) XXX_DiscardUnknown() {
	xxx_messageInfo_Pack.DiscardUnknown(m)
}

var xxx_messageInfo_Pack proto.InternalMessageInfo

func (m *Pack) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Pack) GetNum() int64 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

type Daily struct {
	LastUpdateTime       *int64   `protobuf:"varint,1,opt,name=lastUpdateTime" json:"lastUpdateTime,omitempty"`
	Sign                 *bool    `protobuf:"varint,2,opt,name=sign" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Daily) Reset()         { *m = Daily{} }
func (m *Daily) String() string { return proto.CompactTextString(m) }
func (*Daily) ProtoMessage()    {}
func (*Daily) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{34}
}
func (m *Daily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Daily.Unmarshal(m, b)
}
func (m *Daily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Daily.Marshal(b, m, deterministic)
}
func (dst *Daily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Daily.Merge(dst, src)
}
func (m *Daily) XXX_Size() int {
	return xxx_messageInfo_Daily.Size(m)
}
func (m *Daily) XXX_DiscardUnknown() {
	xxx_messageInfo_Daily.DiscardUnknown(m)
}

var xxx_messageInfo_Daily proto.InternalMessageInfo

func (m *Daily) GetLastUpdateTime() int64 {
	if m != nil && m.LastUpdateTime != nil {
		return *m.LastUpdateTime
	}
	return 0
}

func (m *Daily) GetSign() bool {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return false
}

type TestList struct {
	Id                   *int64                      `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	ListPrimitiveInt     []*TestListListPrimitiveInt `protobuf:"bytes,1,rep,name=ListPrimitiveInt" json:"ListPrimitiveInt,omitempty"`
	ListPrimitiveStr     []*TestListListPrimitiveStr `protobuf:"bytes,2,rep,name=ListPrimitiveStr" json:"ListPrimitiveStr,omitempty"`
	ListPrimitiveCom     []*TestListListPrimitiveCom `protobuf:"bytes,3,rep,name=ListPrimitiveCom" json:"ListPrimitiveCom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TestList) Reset()         { *m = TestList{} }
func (m *TestList) String() string { return proto.CompactTextString(m) }
func (*TestList) ProtoMessage()    {}
func (*TestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{35}
}
func (m *TestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestList.Unmarshal(m, b)
}
func (m *TestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestList.Marshal(b, m, deterministic)
}
func (dst *TestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestList.Merge(dst, src)
}
func (m *TestList) XXX_Size() int {
	return xxx_messageInfo_TestList.Size(m)
}
func (m *TestList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestList.DiscardUnknown(m)
}

var xxx_messageInfo_TestList proto.InternalMessageInfo

func (m *TestList) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TestList) GetListPrimitiveInt() []*TestListListPrimitiveInt {
	if m != nil {
		return m.ListPrimitiveInt
	}
	return nil
}

func (m *TestList) GetListPrimitiveStr() []*TestListListPrimitiveStr {
	if m != nil {
		return m.ListPrimitiveStr
	}
	return nil
}

func (m *TestList) GetListPrimitiveCom() []*TestListListPrimitiveCom {
	if m != nil {
		return m.ListPrimitiveCom
	}
	return nil
}

type TestMap struct {
	Id                   *BaseInfo                    `protobuf:"bytes,7,opt,name=id" json:"id,omitempty"`
	MapPrimitiveIntInt   []*TestMapMapPrimitiveIntInt `protobuf:"bytes,1,rep,name=MapPrimitiveIntInt" json:"MapPrimitiveIntInt,omitempty"`
	MapPrimitiveIntStr   []*TestMapMapPrimitiveIntStr `protobuf:"bytes,2,rep,name=MapPrimitiveIntStr" json:"MapPrimitiveIntStr,omitempty"`
	MapPrimitiveStrInt   []*TestMapMapPrimitiveStrInt `protobuf:"bytes,3,rep,name=MapPrimitiveStrInt" json:"MapPrimitiveStrInt,omitempty"`
	MapPrimitiveStrStr   []*TestMapMapPrimitiveStrStr `protobuf:"bytes,4,rep,name=MapPrimitiveStrStr" json:"MapPrimitiveStrStr,omitempty"`
	MapPrimitiveIntCom   []*TestMapMapPrimitiveIntCom `protobuf:"bytes,5,rep,name=MapPrimitiveIntCom" json:"MapPrimitiveIntCom,omitempty"`
	MapPrimitiveStrCom   []*TestMapMapPrimitiveStrCom `protobuf:"bytes,6,rep,name=MapPrimitiveStrCom" json:"MapPrimitiveStrCom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TestMap) Reset()         { *m = TestMap{} }
func (m *TestMap) String() string { return proto.CompactTextString(m) }
func (*TestMap) ProtoMessage()    {}
func (*TestMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_15942434989900d1, []int{36}
}
func (m *TestMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMap.Unmarshal(m, b)
}
func (m *TestMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMap.Marshal(b, m, deterministic)
}
func (dst *TestMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMap.Merge(dst, src)
}
func (m *TestMap) XXX_Size() int {
	return xxx_messageInfo_TestMap.Size(m)
}
func (m *TestMap) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMap.DiscardUnknown(m)
}

var xxx_messageInfo_TestMap proto.InternalMessageInfo

func (m *TestMap) GetId() *BaseInfo {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveIntInt() []*TestMapMapPrimitiveIntInt {
	if m != nil {
		return m.MapPrimitiveIntInt
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveIntStr() []*TestMapMapPrimitiveIntStr {
	if m != nil {
		return m.MapPrimitiveIntStr
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveStrInt() []*TestMapMapPrimitiveStrInt {
	if m != nil {
		return m.MapPrimitiveStrInt
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveStrStr() []*TestMapMapPrimitiveStrStr {
	if m != nil {
		return m.MapPrimitiveStrStr
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveIntCom() []*TestMapMapPrimitiveIntCom {
	if m != nil {
		return m.MapPrimitiveIntCom
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveStrCom() []*TestMapMapPrimitiveStrCom {
	if m != nil {
		return m.MapPrimitiveStrCom
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerDatabaseInfo)(nil), "netproto.PlayerDatabaseInfo")
	proto.RegisterType((*PlayerDatapets)(nil), "netproto.PlayerDatapets")
	proto.RegisterType((*PlayerDatadaily)(nil), "netproto.PlayerDatadaily")
	proto.RegisterType((*PlayerDatapacks)(nil), "netproto.PlayerDatapacks")
	proto.RegisterType((*PlayerInfoserverTime)(nil), "netproto.PlayerInfoserverTime")
	proto.RegisterType((*PlayerInfoserverName)(nil), "netproto.PlayerInfoserverName")
	proto.RegisterType((*BaseInfoid)(nil), "netproto.BaseInfoid")
	proto.RegisterType((*BaseInfoname)(nil), "netproto.BaseInfoname")
	proto.RegisterType((*BaseInfolevel)(nil), "netproto.BaseInfolevel")
	proto.RegisterType((*BaseInfogold)(nil), "netproto.BaseInfogold")
	proto.RegisterType((*BaseInfoexp)(nil), "netproto.BaseInfoexp")
	proto.RegisterType((*Petid)(nil), "netproto.Petid")
	proto.RegisterType((*Petlevel)(nil), "netproto.Petlevel")
	proto.RegisterType((*Petpack)(nil), "netproto.Petpack")
	proto.RegisterType((*Packid)(nil), "netproto.Packid")
	proto.RegisterType((*Packnum)(nil), "netproto.Packnum")
	proto.RegisterType((*DailylastUpdateTime)(nil), "netproto.DailylastUpdateTime")
	proto.RegisterType((*Dailysign)(nil), "netproto.Dailysign")
	proto.RegisterType((*TestListid)(nil), "netproto.TestListid")
	proto.RegisterType((*TestListListPrimitiveInt)(nil), "netproto.TestListListPrimitiveInt")
	proto.RegisterType((*TestListListPrimitiveStr)(nil), "netproto.TestListListPrimitiveStr")
	proto.RegisterType((*TestListListPrimitiveCom)(nil), "netproto.TestListListPrimitiveCom")
	proto.RegisterType((*TestMapid)(nil), "netproto.TestMapid")
	proto.RegisterType((*TestMapMapPrimitiveIntInt)(nil), "netproto.TestMapMapPrimitiveIntInt")
	proto.RegisterType((*TestMapMapPrimitiveIntStr)(nil), "netproto.TestMapMapPrimitiveIntStr")
	proto.RegisterType((*TestMapMapPrimitiveStrInt)(nil), "netproto.TestMapMapPrimitiveStrInt")
	proto.RegisterType((*TestMapMapPrimitiveStrStr)(nil), "netproto.TestMapMapPrimitiveStrStr")
	proto.RegisterType((*TestMapMapPrimitiveIntCom)(nil), "netproto.TestMapMapPrimitiveIntCom")
	proto.RegisterType((*TestMapMapPrimitiveStrCom)(nil), "netproto.TestMapMapPrimitiveStrCom")
	proto.RegisterType((*PlayerData)(nil), "netproto.PlayerData")
	proto.RegisterType((*PlayerInfo)(nil), "netproto.PlayerInfo")
	proto.RegisterType((*BaseInfo)(nil), "netproto.BaseInfo")
	proto.RegisterType((*Pet)(nil), "netproto.Pet")
	proto.RegisterType((*Pack)(nil), "netproto.Pack")
	proto.RegisterType((*Daily)(nil), "netproto.Daily")
	proto.RegisterType((*TestList)(nil), "netproto.TestList")
	proto.RegisterType((*TestMap)(nil), "netproto.TestMap")
}

func init() { proto.RegisterFile("playerdata.proto", fileDescriptor_playerdata_15942434989900d1) }

var fileDescriptor_playerdata_15942434989900d1 = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xdd, 0x4e, 0xdb, 0x30,
	0x14, 0xc7, 0xd5, 0x26, 0x81, 0xf6, 0x30, 0x4a, 0xe5, 0x71, 0x11, 0x6e, 0xb6, 0x2e, 0xdb, 0x50,
	0xa5, 0xb1, 0xb2, 0xb1, 0xab, 0xed, 0x62, 0x48, 0x2b, 0x9b, 0x84, 0x04, 0x28, 0x4a, 0xe0, 0x01,
	0x3c, 0xe2, 0xa1, 0xac, 0xf9, 0x52, 0x62, 0x2a, 0x78, 0x85, 0xbd, 0xca, 0xde, 0x62, 0x4f, 0x36,
	0xd9, 0xb1, 0x9b, 0x90, 0x38, 0xd4, 0x5c, 0x54, 0x72, 0xed, 0xf3, 0xff, 0x9d, 0x0f, 0x3b, 0xe7,
	0xc0, 0x38, 0x8b, 0xf0, 0x3d, 0xc9, 0x03, 0x4c, 0xf1, 0x2c, 0xcb, 0x53, 0x9a, 0xa2, 0x41, 0x42,
	0x28, 0x5f, 0x39, 0x67, 0x80, 0x5c, 0x7e, 0x7a, 0x82, 0x29, 0xfe, 0x89, 0x0b, 0x72, 0x9a, 0xfc,
	0x4a, 0xd1, 0x18, 0x8c, 0x05, 0xb9, 0xb7, 0x7b, 0x93, 0xde, 0xd4, 0xf2, 0xd8, 0x12, 0xbd, 0x01,
	0x63, 0x89, 0x23, 0xbb, 0x3f, 0xe9, 0x4d, 0xb7, 0x8e, 0xd0, 0x4c, 0xea, 0x67, 0xdf, 0x84, 0xc4,
	0x63, 0xc7, 0xce, 0x1c, 0x46, 0x15, 0x2d, 0x23, 0xb4, 0x50, 0x90, 0x5e, 0xd6, 0x49, 0xdb, 0x15,
	0xc9, 0x25, 0xb4, 0x84, 0xfc, 0x80, 0x9d, 0x0a, 0x12, 0xe0, 0x30, 0xba, 0x57, 0x50, 0x5e, 0xd5,
	0x29, 0x3b, 0x15, 0xe5, 0x84, 0xd9, 0x97, 0x9c, 0xef, 0x75, 0x4e, 0x86, 0xaf, 0x17, 0xaa, 0x68,
	0x26, 0x75, 0xce, 0xa8, 0x16, 0x0d, 0xbe, 0x5e, 0x94, 0x98, 0x2f, 0xb0, 0x5b, 0x62, 0x58, 0x9a,
	0x05, 0xc9, 0x97, 0x24, 0xbf, 0x0c, 0x63, 0xa2, 0x60, 0x8d, 0x2b, 0x96, 0xd1, 0xa9, 0xbd, 0xc0,
	0xeb, 0xb4, 0xc3, 0x52, 0xfb, 0x01, 0x40, 0x16, 0x37, 0x0c, 0xb4, 0xbc, 0x1d, 0xc1, 0x33, 0xa9,
	0x48, 0x74, 0xbd, 0x7c, 0x82, 0x6d, 0xa9, 0x89, 0xc8, 0x92, 0x44, 0x8f, 0x8b, 0xac, 0x96, 0xa3,
	0x9b, 0x34, 0x0a, 0xb4, 0x34, 0x1f, 0x61, 0x4b, 0x6a, 0xc8, 0x5d, 0xa6, 0x25, 0x79, 0x07, 0x96,
	0x4b, 0xa8, 0x66, 0xf2, 0x33, 0x18, 0xb8, 0x84, 0xea, 0xe7, 0xf0, 0x1e, 0x36, 0x5d, 0x42, 0xd9,
	0xb3, 0xd0, 0x32, 0x3f, 0x80, 0x0d, 0xf6, 0x24, 0x34, 0x83, 0x61, 0x70, 0x7c, 0xbd, 0x48, 0x6e,
	0x63, 0x2d, 0xf3, 0xcf, 0xf0, 0x9c, 0xbf, 0xdb, 0x08, 0x17, 0xf4, 0x2a, 0x0b, 0x30, 0x25, 0xda,
	0x2f, 0xec, 0x10, 0x86, 0x5c, 0x5a, 0x84, 0x37, 0xc9, 0xe3, 0x82, 0xc1, 0xea, 0x59, 0x5d, 0x92,
	0x82, 0x9e, 0x85, 0x85, 0x6e, 0x65, 0xbf, 0x82, 0x2d, 0x15, 0xec, 0xe7, 0xe6, 0x61, 0x1c, 0xd2,
	0x70, 0x49, 0x4e, 0x13, 0xaa, 0x55, 0xba, 0x2e, 0xbd, 0x4f, 0x73, 0xad, 0x27, 0x7a, 0xd9, 0xa1,
	0x9f, 0xa7, 0xaa, 0xea, 0xee, 0xd7, 0x3f, 0xe8, 0xdd, 0xda, 0x07, 0xbd, 0x6a, 0x05, 0xb2, 0x55,
	0x0d, 0x19, 0xf5, 0x1c, 0x67, 0xca, 0x32, 0xe8, 0xf5, 0xbb, 0x63, 0xd8, 0x13, 0x90, 0x73, 0x9c,
	0xd5, 0x0b, 0xa3, 0x5b, 0x9b, 0x4e, 0x80, 0x6e, 0x71, 0xd4, 0x00, 0x9f, 0xe6, 0x8d, 0x08, 0x86,
	0x4f, 0x8b, 0xc0, 0xa7, 0x79, 0x23, 0x82, 0x61, 0x57, 0x04, 0x7e, 0x57, 0x0a, 0xea, 0xfb, 0xd1,
	0x2b, 0xec, 0x55, 0x57, 0x54, 0x0d, 0xe8, 0xf0, 0x69, 0x97, 0xfe, 0xaf, 0x07, 0x50, 0xed, 0xa1,
	0x19, 0x0c, 0xe4, 0xc8, 0xe3, 0x34, 0x75, 0x40, 0x2b, 0x1b, 0x74, 0x00, 0x26, 0x1b, 0x6a, 0x76,
	0x7f, 0x62, 0x4c, 0xb7, 0x8e, 0x6c, 0x95, 0x1f, 0x76, 0xee, 0x71, 0x2b, 0xf4, 0x16, 0x2c, 0x3e,
	0xbd, 0x6c, 0x43, 0x3d, 0xa4, 0xca, 0x53, 0x74, 0x08, 0x16, 0x1f, 0x4e, 0xb6, 0xc9, 0xa9, 0x7b,
	0x4a, 0x2a, 0x33, 0xf0, 0x4a, 0x3b, 0xe7, 0x4c, 0xe6, 0xc0, 0x63, 0x7a, 0x01, 0x50, 0x0d, 0x25,
	0x9e, 0x85, 0xe1, 0xd5, 0x76, 0xaa, 0x73, 0x36, 0x78, 0xc4, 0xbd, 0xd5, 0x76, 0x9c, 0xdf, 0x30,
	0x90, 0x99, 0xa2, 0x11, 0xf4, 0xc3, 0x40, 0x30, 0xfa, 0x61, 0x80, 0x10, 0x98, 0x49, 0xa5, 0xe2,
	0x6b, 0xb4, 0x0b, 0x16, 0x6f, 0xb2, 0x3c, 0x2b, 0xcb, 0x2b, 0xff, 0x30, 0x4b, 0x36, 0x09, 0x6c,
	0x93, 0x6f, 0x9a, 0x72, 0x2a, 0x90, 0xbb, 0xcc, 0xb6, 0xca, 0xbb, 0x27, 0x77, 0x99, 0x73, 0x0c,
	0x86, 0x4b, 0x68, 0xcb, 0xcd, 0x0a, 0xd9, 0x6f, 0x20, 0x59, 0xbe, 0xc2, 0x0f, 0x5f, 0x3b, 0x53,
	0x30, 0x59, 0x5f, 0x6d, 0x11, 0xc6, 0x60, 0x24, 0xb7, 0xb1, 0x6c, 0x5a, 0xc9, 0x6d, 0xec, 0xcc,
	0xc1, 0xe2, 0x55, 0x46, 0xfb, 0x30, 0x7a, 0xd8, 0x56, 0x85, 0xac, 0xb1, 0xcb, 0xdc, 0xb1, 0x1e,
	0x2a, 0x5a, 0x25, 0x5f, 0x3b, 0x7f, 0xfa, 0x30, 0x90, 0xad, 0x47, 0xf8, 0xdc, 0x5c, 0xf9, 0xbc,
	0x80, 0x71, 0xb3, 0x1d, 0xda, 0x3d, 0x7e, 0x85, 0x4e, 0x75, 0x85, 0x5d, 0x8d, 0xd3, 0x6b, 0x69,
	0x5b, 0x3c, 0x9f, 0xe6, 0xe2, 0xa1, 0xad, 0xe3, 0xf9, 0x34, 0xf7, 0x5a, 0xda, 0x16, 0x6f, 0x9e,
	0xc6, 0xb6, 0xa1, 0xc5, 0x9b, 0xa7, 0xb1, 0xd7, 0xd2, 0x3a, 0x7f, 0x4d, 0xd8, 0x14, 0xdf, 0x24,
	0x72, 0x56, 0xb5, 0x50, 0x7f, 0x32, 0xac, 0x3e, 0x3e, 0xa0, 0x76, 0x53, 0x14, 0x15, 0x7a, 0xfd,
	0x30, 0x02, 0x65, 0xff, 0xf4, 0x14, 0x72, 0x05, 0xb4, 0x2a, 0xd3, 0x5a, 0x28, 0xab, 0x93, 0x42,
	0xde, 0x84, 0x96, 0xcd, 0x53, 0xd4, 0xea, 0x71, 0x68, 0x69, 0xea, 0x29, 0xe4, 0x0a, 0x28, 0x8b,
	0xd4, 0xd4, 0x83, 0xb6, 0x22, 0x15, 0xfd, 0xb8, 0x9d, 0x3e, 0xbb, 0x55, 0x4b, 0x2f, 0x7d, 0x76,
	0xad, 0x0a, 0xb9, 0x22, 0x52, 0x06, 0xdd, 0xd0, 0x8b, 0xb4, 0x05, 0x2d, 0xf7, 0xfe, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x60, 0x4a, 0x56, 0x15, 0x74, 0x0c, 0x00, 0x00,
}
